# Numpy - Vectors and Matrices

In [6]:
import numpy as np

In [7]:
v = np.array([[1,2],[3,4]])

In [8]:
v

array([[1, 2],
       [3, 4]])

In [9]:
l = [[1,2],[2,2]]

In [10]:
l[0]

[1, 2]

In [11]:
l[0][0]

1

In [12]:
v[0]

array([1, 2])

In [13]:
v[0][0]

1

In [14]:
v[0,0]

1

In [27]:
 m = np.matrix([[1,2],[2,2]])

In [29]:
m

matrix([[1, 2],
        [2, 2]])

In [31]:
m[0,0]

1

In [33]:
for i in m:
    print i

[[1 2]]
[[2 2]]


In [35]:
z = np.zeros(10)

In [36]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [39]:
z1=np.zeros([10,10])

In [41]:
z1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [43]:
o=np.ones([10,10])

In [45]:
o

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [49]:
r = np.random.random((10,10))

In [51]:
r

array([[ 0.88730864,  0.95377601,  0.57186941,  0.37192022,  0.26470708,
         0.37553176,  0.77178063,  0.3805895 ,  0.95626876,  0.771851  ],
       [ 0.0724088 ,  0.79317347,  0.30999263,  0.66164054,  0.74001056,
         0.91780378,  0.42583799,  0.31850133,  0.99019143,  0.51983697],
       [ 0.42658987,  0.29589156,  0.6539768 ,  0.61720821,  0.09403473,
         0.30694626,  0.68853058,  0.06440898,  0.25208583,  0.03717003],
       [ 0.10301359,  0.67054865,  0.06494978,  0.58037749,  0.18000954,
         0.35355178,  0.653443  ,  0.82333792,  0.98183817,  0.04349338],
       [ 0.25704404,  0.37525555,  0.98577339,  0.62499606,  0.44136361,
         0.31392283,  0.12826112,  0.56632187,  0.62295768,  0.35444685],
       [ 0.61255816,  0.37436585,  0.6376283 ,  0.55110758,  0.54174398,
         0.57811065,  0.77522166,  0.21978311,  0.82473105,  0.62222569],
       [ 0.54332011,  0.23558691,  0.55378649,  0.94930497,  0.47913639,
         0.37787019,  0.6891804 ,  0.42147914

Generate random number (of gaussian function mean=0, sd=1) - use randn
-note do not pass list or tuple in function

In [15]:
G = np.random.randn(10,10)

In [16]:
G

array([[ 0.38728199,  0.52815785, -0.3961958 , -2.34831893,  0.98255943,
        -2.72316645,  1.39775468, -0.07187525,  1.17435863,  0.77175458],
       [ 0.62971939, -0.33514041, -0.97205411, -0.09462981, -1.45706258,
        -1.12050181, -1.36663955,  1.04895909,  0.34867172,  1.14185062],
       [ 0.57801202, -1.03621366,  0.10364134, -1.53792962,  0.46757031,
        -0.96545685, -0.18808886,  0.02531391, -0.68988675,  0.89555985],
       [ 1.17565247,  1.00363741,  0.59377358,  0.49379611,  0.21429292,
         1.92001965,  0.09347655,  0.82854021,  1.02686223,  0.32563975],
       [ 0.62927275, -0.71850332, -0.04175857, -1.75329891, -0.36734031,
        -0.76762007,  1.46775008,  1.12414768,  0.8025745 , -1.43871492],
       [-1.40830987,  1.14171571,  0.64214186,  1.26580605, -0.03665601,
        -1.92479336, -1.01702403, -0.11764118, -0.7834991 ,  0.45350438],
       [ 0.2770577 ,  0.0851497 , -0.08231672, -0.07920551,  1.43644404,
         0.95044962,  1.99948992, -2.47594101

In [17]:
G.mean()

0.1282981753424644

In [18]:
G.var()

1.1207422968121081

    More Matrix operations