# Numpy - List vs Arrays

In [5]:
import numpy as np

In [15]:
l = [1,2,3]

In [2]:
l

[1, 2, 3]

In [7]:
a = np.array([1,2,3]);

In [9]:
a

array([1, 2, 3])

In [16]:
l + l

[1, 2, 3, 1, 2, 3]

In [17]:
a + a 

array([2, 4, 6])

In [19]:
for i in l:
    print i

1
2
3


In [21]:
for i in a:
    print i

1
2
3


In [23]:
l2=[]

In [25]:
for i in l:
    l2.append(i + i)

In [26]:
l2

[2, 4, 6]

In [28]:
l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [30]:
a**2

array([1, 4, 9])

In [32]:
np.sqrt(a)

array([ 1.        ,  1.41421356,  1.73205081])

In [34]:
np.log(a)

array([ 0.        ,  0.69314718,  1.09861229])

In [36]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692])

-In arrays we can do vector addition directly e.g a +a 
-In arrays we can perform math operations directly
-In python we need to use loops(python loops are slow) for performing any operations on list elements 