# Numpy - Vectors and Matrices

In [1]:
import numpy as np

In [8]:
v = np.array([[1,2],[3,4]])

In [11]:
v

array([[1, 2],
       [3, 4]])

In [13]:
l = [[1,2],[2,2]]

In [15]:
l[0]

[1, 2]

In [17]:
l[0][0]

1

In [19]:
v[0]

array([1, 2])

In [21]:
v[0][0]

1

In [23]:
v[0,0]

1

In [27]:
 m = np.matrix([[1,2],[2,2]])

In [29]:
m

matrix([[1, 2],
        [2, 2]])

In [31]:
m[0,0]

1

In [33]:
for i in m:
    print i

[[1 2]]
[[2 2]]


In [35]:
z = np.zeros(10)

In [36]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [39]:
z1=np.zeros([10,10])

In [41]:
z1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [43]:
o=np.ones([10,10])

In [45]:
o

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [49]:
r = np.random.random((10,10))

In [51]:
r

array([[ 0.88730864,  0.95377601,  0.57186941,  0.37192022,  0.26470708,
         0.37553176,  0.77178063,  0.3805895 ,  0.95626876,  0.771851  ],
       [ 0.0724088 ,  0.79317347,  0.30999263,  0.66164054,  0.74001056,
         0.91780378,  0.42583799,  0.31850133,  0.99019143,  0.51983697],
       [ 0.42658987,  0.29589156,  0.6539768 ,  0.61720821,  0.09403473,
         0.30694626,  0.68853058,  0.06440898,  0.25208583,  0.03717003],
       [ 0.10301359,  0.67054865,  0.06494978,  0.58037749,  0.18000954,
         0.35355178,  0.653443  ,  0.82333792,  0.98183817,  0.04349338],
       [ 0.25704404,  0.37525555,  0.98577339,  0.62499606,  0.44136361,
         0.31392283,  0.12826112,  0.56632187,  0.62295768,  0.35444685],
       [ 0.61255816,  0.37436585,  0.6376283 ,  0.55110758,  0.54174398,
         0.57811065,  0.77522166,  0.21978311,  0.82473105,  0.62222569],
       [ 0.54332011,  0.23558691,  0.55378649,  0.94930497,  0.47913639,
         0.37787019,  0.6891804 ,  0.42147914

Generate random number (of gaussian function mean=0, sd=1) - use randn
-note do not pass list or tuple in function

In [53]:
G = np.random.randn(10,10)

In [55]:
G

array([[ 1.23023927, -1.96849588, -2.02385984, -0.99321011,  0.69020915,
         0.47763869,  1.31441438,  0.60164031,  0.39261339, -0.15650932],
       [-1.65877974, -0.58083608, -0.28458527,  0.35478957,  2.1668924 ,
        -0.29552305,  1.46991967, -0.07915526,  0.3111421 , -0.71544902],
       [-0.72634508,  1.22286954, -0.99763087,  0.33244068,  0.21999471,
        -0.36248969,  1.14684623,  0.94993295, -0.16010303, -1.05311492],
       [ 0.84670868,  0.6567491 ,  2.34734734,  1.27917492,  0.1836628 ,
         0.80998348, -0.02024189,  1.65822424,  0.65067742,  0.19380327],
       [-1.14109791,  0.48540457, -0.07897413, -0.08489962, -1.52904874,
         0.27733019, -0.59404511,  1.53059688, -2.05584548, -1.0184165 ],
       [-0.7216489 ,  0.16465337, -0.59390821,  0.98680523, -0.16446495,
         0.82229793,  2.22345628,  1.22943718, -0.72845124, -0.15413191],
       [-0.77513862, -0.19821242, -0.26511199,  0.60060918, -0.10939358,
        -0.69814102,  1.09212057,  1.27993107

In [58]:
G.mean()

0.098343796817048232

In [59]:
G.var()

1.0464471902636097