In [3]:
import numpy as np

In [4]:
x = np.array([-2,-1,1,3])

In [5]:
x

array([-2, -1,  1,  3])

In [6]:

abs(x)

array([2, 1, 1, 3])

In [7]:
min(x)

-2

In [8]:
max(x)

3

In [9]:
np.absolute(x)

array([2, 1, 1, 3])

In [10]:
np.linspace(2,10,20)

array([  2.        ,   2.42105263,   2.84210526,   3.26315789,
         3.68421053,   4.10526316,   4.52631579,   4.94736842,
         5.36842105,   5.78947368,   6.21052632,   6.63157895,
         7.05263158,   7.47368421,   7.89473684,   8.31578947,
         8.73684211,   9.15789474,   9.57894737,  10.        ])

In [11]:
np.log2(abs(x))

array([ 1.       ,  0.       ,  0.       ,  1.5849625])

In [12]:
a = np.arange(5)

In [13]:
a

array([0, 1, 2, 3, 4])

In [14]:
b=np.empty(5)

In [15]:
b

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.multiply(a,b)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
x = np.arange(1,6)


In [18]:
x

array([1, 2, 3, 4, 5])

In [19]:
np.add.reduce(x)

15

In [20]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [21]:

np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [22]:
x

array([1, 2, 3, 4, 5])

In [23]:
a = np.arange(1000000)

In [24]:
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [25]:
big_data = np.random.rand(10000000)

In [26]:
%timeit np.sum(big_data)

10 loops, best of 3: 21.1 ms per loop


In [27]:
x = np.random.random((3,4))

In [28]:
x

array([[ 0.52303731,  0.67582476,  0.80500895,  0.93329619],
       [ 0.10305234,  0.0855474 ,  0.72367842,  0.63382682],
       [ 0.217015  ,  0.27635986,  0.30071014,  0.79457166]])

In [29]:
np.sum(x,axis=1)

array([ 2.93716721,  1.54610498,  1.58865666])

In [30]:

np.argmax(x,axis=1)

array([3, 2, 3], dtype=int64)

In [31]:
x = np.array([-2,-1,11,3])

In [32]:
np.argmax(x)

2

In [33]:
x = np.array([1,2,3,4,5])

In [34]:

x[x < 3]

array([1, 2])

In [35]:
for i in x:
    if i<3:
        print i

1
2


In [36]:
x[x>3]

array([4, 5])

In [37]:
x[x!=3]

array([1, 2, 4, 5])

In [38]:
x[x==3]

array([3])

In [39]:
x = np.array([0,2,3,41,0,1])

In [40]:
x

array([ 0,  2,  3, 41,  0,  1])

In [41]:
np.count_nonzero(x)

4

In [42]:
np.any(x > 3)

True

In [43]:
np.all(x >= 0)

True

In [44]:
np.all(x>0)

False

In [45]:
x[ (x<2) | ( x > 4)]

array([ 0, 41,  0,  1])

In [46]:

rand = np.random.RandomState(42)

In [47]:
x = rand.randint(100, size=10)

In [48]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [49]:
ind = [2,3,4]

In [50]:
x[ind]

array([14, 71, 60])

In [51]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [52]:

row = np.array([0,1,2])
col = np.array([2,1,3])

In [53]:
row

array([0, 1, 2])

In [54]:
col

array([2, 1, 3])

In [55]:
X = np.arange(12).reshape((3,4))

In [56]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
X[row,col]

array([ 2,  5, 11])

In [58]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
Y = np.arange(16).reshape((4,4))

In [60]:
Y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
Y[range(4),range(4)]

array([ 0,  5, 10, 15])

In [62]:
list(range(4))

[0, 1, 2, 3]

In [66]:
data = rand.randint(10000,size=100)

In [67]:
data

array([ 606, 3170,  699, 5088, 9331,  190,  980, 2975, 6102, 1184, 3327,
       3394, 8319, 1816, 5854, 6709,  569, 5442, 1895, 2733, 3863, 7455,
       4014, 1686, 3009, 7806,  154, 1409,  784, 8096, 7560, 7343, 7206,
       5596, 5801, 2806,  537, 5986, 1841, 8716, 6971, 5625, 2950, 7992,
       4780, 2368, 6655, 8173, 4495, 9163, 6002, 6614, 9358, 5919,  853,
       4146, 3769,  574, 1148, 6293, 6457, 7509, 9907, 4777, 3854, 2491,
       3124, 5691, 3051,    4, 5222, 5315, 4869,  876, 9183, 7027, 4142,
       6966, 7079, 7987, 6799, 4465,  635, 1693, 9874, 4752, 8311,  830,
       5177, 9561, 8932, 8308, 5949, 2838, 1150, 7560, 1931, 9204, 1664,
       1081])